<template>
    <div id="mainContent">
        <p>
            <br>
        </p>
        <h1 align="center">
            <strong>
                <em>
                    Butterfly
                    House Rules
                </em>
            </strong>
        </h1>
        <p align="center">
            <a href="~/static/BH residency and program rules PDF.pdf">Download PDF</a>
        </p>
        <div
            class="box"
        >At Butterfly House we have established rules of conduct that all residents are expected to adhere to. The following pages outline rules and expectations regarding safety, respect for self and others, honesty to self and others, residency fees, medication management, living space maintenance, transportation, employment/community service, relationships, meeting attendance, drug testing, probation/parole/court orders, and general household rules.
            <br>
        </div>
        <p align="center">&nbsp;</p>
        <p>
            <strong>Safety:</strong>
            <br>I agree that I will not bring illicit drugs or alcohol in any form onto the property of Butterfly House. I will not bring prescription medications that have not been prescribed to me onto the property of Butterfly House. I will not bring prescribed medications that are on the “not-allowed” list onto the property of Butterfly House. I will not bring homemade or purchased paraphernalia onto the property of Butterfly House. I understand that if I violate this rule, it is grounds for my immediate expulsion from Butterfly House.
            <br>I agree that I will not engage in the use of alcohol or illicit/illegal drugs, or the abuse of prescription medications (including those prescribed to me) while a resident of Butterfly House. I understand that if use or abuse is suspected, I will be given a UA, PBT (breathalyzer), or ETG (lab test for alcohol) and my prescription medications will be counted to verify compliance with prescription. I understand that if the test is positive, it is grounds for my immediate expulsion from Butterfly House and I will be responsible for paying the fee for the UA ($20).
            <br>I agree that I will not light a cigarette or lighter, smoke, or use chewing tobacco inside of Butterfly House. I agree that I will only use tobacco products in designated smoking areas. I agree that I will not possess or use cigarette rolling supplies including, but not limited to rolling papers, loose tobacco, and rolling devices. I will not throw cigarette butts or cigarette package wrappers on the property. I will not leave my lit cigarette or lighter unattended and I understand that if I leave my lighter unattended, it will be confiscated and will not be returned to me.
            <br>I agree that I will not bring explosive items (firecrackers, etc.) or weapons of any kind onto the grounds of Butterfly House. I will not use any form of accelerant on an open flame on the grounds of Butterfly House. I understand that if I violate this rule, it is grounds for my immediate expulsion from Butterfly House.
            <br>I agree that I will not correspond with jail or prison inmates. I will not receive from, or send phone calls, letters, cards, or pictures to anyone incarcerated in jail or prison. I will not use an alternate address to send to, or receive mail from, anyone incarcerated in jail or prison. I will not participate in a 3-way call with an inmate. I will not ask others to give messages to an inmate in jail or prison. I UNDERSTAND THAT THIS IS A MAJOR RULE VIOLATION and will result in my immediate expulsion from Butterfly House!
            <br>I agree that I am ultimately responsible for the actions of my visiting friends or family members. I will not leave children unattended, ever! I will not allow visitors inside Butterfly House without prior approval from staff. I will not allow visitors to enter the upstairs living areas without staff knowledge and permission.
            <br>I agree that if I receive a package in the mail, I will open it with a staff person present. I agree that if I receive an item in the mail that is detrimental to my recovery, I will give the item to staff for safekeeping.
            <br>I agree that if I witness or have knowledge of an unsafe situation concerning myself or another resident, I will report it to staff.
            <br>I agree that if I have knowledge of an unsafe situation concerning the property of Butterfly House, I will report it to staff.
            <br>_____ I have read, understand, and agree to follow the rules listed above.
            <br>2
            <br>
            <strong>Respect for self and others:
                <br>
            </strong>I will show respect for others including residents, visitors, staff, and volunteers. Disrespectful behavior includes swearing, yelling, verbal abuse, physical threats, and aggressiveness. Note: The consequence for violence or threat of violence towards another resident, staff, meeting participant, or volunteer staff, is immediate expulsion from residency at Butterfly House. I will respect my housemate’s right to privacy and anonymity.
            <br>I will be courteous regarding noise levels of conversations with others, telephone calls and TV noise levels. I will answer the phone by saying “Hello, ____________ speaking”. I will not give out information about other residents. I will take a message for residents who are not present, including the date, time of call, the caller’s name, and phone number.
            <br>I will not engage in watching pornographic movies or the viewing of pornography of any kind. I will not wear clothing that is determined to be sexually suggestive or that displays pornographic images. I will not have an exclusive or sexual relationship with any other resident or volunteer of Butterfly House. I will not possess “sex toys” or other paraphernalia while a resident of Butterfly House.
            <br>I will respect all property of all Butterfly House residents, staff, and volunteers. I agree that I will not flush tampons, paper, grease or cigarette butts down the toilets. I will not pour grease, paints, or dyes down the drains. I will not dye my hair or tie dye fabric at Butterfly House. If I break or damage an item that is not my own, I will report it and pay any damages as determined by staff.
            <br>I will not wear clothing, hats, or jewelry which advertises alcohol, drugs, or violence. I will not use can coolers or other items that advertise alcohol, drugs or violence. I will not display calendars, photographs, pictures, or other items in my room that advertise alcohol, drugs, or violence.
            <br>I will maintain personal hygiene and comply with all of my doctor’s recommendations regarding physical and mental health care medications. If my doctor prescribes medication that is not allowed at Butterfly House, I will consult with my doctor to decide if another allowed medication can be substituted, or I will make arrangements to terminate my residency at Butterfly House. I will not covertly use “not allowed” medications while in residency. I will attend all scheduled physical health and mental health care appointments.
            <br>I will respect the boundaries of staff, other residents, their living areas, and property. I will not alter or damage curtains, bedding, wallpaper, carpets or furniture in any way. I will not hang pictures or other items on walls or ceilings without permission from staff. I will not enter another resident’s bedroom without permission. I will not sit or lay on another resident’s bed. I will not enter the staff bedroom for any reason. I will not enter the office unless invited. I understand that I am not allowed to use the office computer.
            <br>While attending meetings, doing community service, or attending community events or outings, I will not wear low cut shirts, short shirts, short skirts, or short shorts. If I wear jeans with holes, I will make sure the holes are not in the seat or crotch area. I will always wear undergarments (bra, underwear). I will not sunbathe outside of the fenced in area of Butterfly House.
            <br>I agree that I will not sleep in any other area of the house, other than in my own bedroom in my own bed. I will not come down to the living room and sleep on the couch or in a chair. I will not sleep in any other resident’s room or in any other resident’s bed.
            <br>I agree that I will identify goals and follow through with accomplishing those goals during my term of stay at Butterfly House. I understand that failure to follow through with this self-sufficiency plan will result in my termination of residency at Butterfly House.
            <br>_____ I have read, understand, and agree to follow the rules listed above.
            <br>3
            <br>
            <strong>Honesty to self and others</strong>
            <br>I understand that I have certain responsibilities concerning myself and other residents with the one of the most important being that we support each other in remaining sober, honest, and responsible to self and others. I understand that violation of “absolute honesty” will initially result in being put on contract and repeated dishonesty or unwillingness to take responsibility for my actions will result in accelerated discharge from residency at Butterfly House.
            <br>I agree that I will not borrow money, cigarettes, or other items from Butterfly House staff and volunteers. I will not “borrow” cigarettes, clothing, money, or other items from my housemates or others including, but not limited to, people at meetings, and people at my place of employment. I will not purchase lottery tickets or gamble in any form while a resident of Butterfly House. I understand that if I violate this rule, I will be put on contract in an effort to correct the behavior. If I continue to violate the rule, the consequence will be expulsion from Butterfly House.
            <br>I understand that I am not allowed to possess a cell phone while in residency at Butterfly House and further agree that I will not hide or covertly use a cell phone while in residency at Butterfly House.
            <br>I understand that I am not allowed to consume “energy drinks” or “energy shots” of any kind, including coffee energy drinks or food supplement energy drinks while I am participating in residency at Butterfly House.
            <br>As a resident of Butterfly House, if I am fortunate enough to have an EBT (Food Share) card, I will be required to purchase all of my own food. I understand that I will not have the option to consume food provided by Butterfly House (community food) and if I run out of Food Share before my month of benefit ends, I will have to go to the food shelf. If I choose to consume community food, it will be considered theft and the violation will be dealt with according to house rules. I understand that I have the option to surrender my Food Share card to Butterfly House to purchase food and in that case, I will have access to “community food”. I understand that food purchased by individual residents and labeled with their name, is not to be used by other residents without permission. I understand that it is against the law to “sell” Food Share benefits. For example, I will not sell or trade my benefits in order to get money to purchase cigarettes or other items.
            <br>I agree that if I have knowledge of an incident involving another resident that compromises the safety or sobriety of others, I will report it to staff immediately.
            <br>I agree that if I have knowledge that an incident of theft has occurred, I will report it to staff. I understand that “unauthorized borrowing” (theft) is grounds for immediate expulsion.
            <br>_____ I have read, understand, and agree to follow the rules listed above.
            <br>Residency fees and other financial obligations
            <br>I agree that I will pay all monies owed to Butterfly House before departure or sign a contract that designates a payment plan for fulfilling my financial obligation. I will then follow through with the terms of the payment plan. I agree that my happiness is my responsibility. If I become dissatisfied or unhappy with my living situation at Butterfly House, I will do what I need to do in order to improve my situation. I will seek out assistance from staff, my sponsor, friends, counselor or peer group.
            <br>I acknowledge that I will not be allowed to go tanning (other than outside in the sun) if my residency fees are not paid in full for the month, if I owe money for fines or restitution, if I owe drug court fees, if I owe library fines, if my personal care needs are not met, if I owe on medical bills, if I owe on dental bills, if I owe court fees, if I owe probation fees, if I owe child support, if I owe transportation fees, if I owe lawyer fees, or money to any other entity.
            <br>I acknowledge that the following violations that will be dealt with, in most cases, by IMMEDIATE EXPULSION from Butterfly House AND there will be no refund of unused residency fees: possession or use of alcohol or other drugs or drug paraphernalia, refusal to take an alcohol or other drug test (UA, PBT, ETG), violence or threat of violence in any form towards staff/volunteers/meeting participants/visitors/other residents, lighting candles, lighting cigarettes on the stove, lighting lighters or smoking inside of the house, possession of a weapon or explosive item, and theft or intentional damage to another resident’s property.
            <br>_____ I have read, understand, and agree to follow the rules listed above.
            <br>4
            <br>
            <strong>Medication management</strong>
            <br>I agree to keep my medications, prescription and over-the-counter, locked in a lock box with the key inaccessible to other residents.
            <br>I agree that all over-the-counter medications must have original label with the name of the medication and dosage instructions on the label. Medications cannot be mixed in the container. I agree that all prescription medications must be kept in the original container with resident’s name, name of medication, dosage instructions, doctor’s name, date and pharmacy name. Medications cannot be mixed in the container.
            <br>I agree that I will take all medications only-as-directed, whether they are over-the-counter, or prescription. I understand that at any time that staff determines necessary, medications may be counted to verify the accuracy of dosage taken.
            <br>I agree that if I take a prescription medication in any manner other than as prescribed, it will be considered “using”. Appropriate action will then be taken. Consequence for using drugs or abusing prescription medications at Butterfly House is immediate expulsion.
            <br>I agree that I will not, under any circumstance, share my medications. Consequence of sharing medications will be immediate expulsion from the Butterfly House program for all residents involved.
            <br>I acknowledge and agree that Butterfly House support staff and Moms and Dads against Meth, Inc. is not responsible for managing my personal prescription medications, dispensing of my personal prescription medications, or securing my personal prescription medications. This is my responsibility as the owner of my personal prescription medication. A lock box will be provided for securing my medications.
            <br>I acknowledge and agree that Butterfly House support staff and Moms and Dads against Meth, Inc. is not responsible for managing my personal over-the-counter medications, dispensing of my personal over-the-counter medications, or securing my personal over-the-counter medications. This is my responsibility as owner of my personal over-the-counter medications. A lock box will be provided for securing my medications.
            <br>_____ I have read, understand, and agree to follow the rules listed above.
            <br>Living space rules and maintenance
            <br>I agree that I will complete all of my assigned chores daily. I will do my part to keep my bedroom and all other property of Butterfly House clean and tidy. I will not store or consume food or beverages in my bedroom or any other rooms except the kitchen.
            <br>I acknowledge that laundry days are Wednesday and Saturday. I acknowledge that clothes are to be washed only in cool or cold water. I acknowledge that during the summer, I will hang my clothes on the clothesline and will not use the dryer. I acknowledge that the Laundromat is next door and if I feel that I must wash my clothes in warm or hot water, or use the dryer, I will go to the Laundromat for that purpose.
            <br>I understand that TV’s, phones, and computers are not allowed in the bedrooms at any time. I understand that Butterfly House is not responsible for lost, damaged or stolen items. Upon exit, I understand that my personal belongings must be picked up within 30 days. I understand that Butterfly House is not responsible for items that I have left behind.
            <br>_____ I have read, understand, and agree to follow the rules listed above.
            <br>5
            <br>
            <strong>Employment/ community service</strong>
            <br>I agree that I will seek employment immediately upon admittance to Butterfly House. I will apply for full time, temporary employment, and as many part-time jobs as necessary to equal full time employment (35-40 hours per week). If I obtain temporary employment, I will continue to seek full time permanent employment. I will not apply for jobs that have a negative impact on my recovery, such as bartender or waitress in an establishment that serves alcohol. I agree to accept all positions of employment offered to me from a job application.
            <br>I agree that I will supply staff with all requested copies of receipts and paycheck information. I agree that I will supply employment search information to staff for purpose of verification.
            <br>I agree that I am not allowed to walk out on a job. If I must leave for medical reasons or emergency, I will not leave without notifying a supervisor. If I must quit my job for medical or emergency reasons, I will give at least 1 weeks notice (preferably 2 weeks notice). I agree that I will not take time off from employment without notifying Butterfly House staff first. I will not get off early (not even 15 minutes), go in late, or ask for a day off, etc. without notifying Butterfly House staff FIRST. If I am unable to work on a particular day (sickness, unexpected admittance to jail, sudden fleeing from Butterfly House) I will call my employer. If I am employed through a temp agency, I will call them also.
            <br>I agree that on days that I am scheduled to work, I will be prepared to work. I will dress appropriately and bring a lunch. If I am not allowed to use an I-Pod, MP3 player, etc., I will not bring one to use covertly. I will not ask to use a co-worker’s cell phone. I will not borrow money or “bum” cigarettes from my co-workers. I will smoke only at designated break times, and in designated smoking areas. I will not take longer breaks than are allowed.
            <br>I agree that I will perform all community service assigned to me by staff. I will also seek out community service opportunities on my own in order to fulfill requirements. I understand that if I am not employed within 2 weeks of admittance to Butterfly House, I am required to do 25 hours of community service in addition to 15 hours of job search per week until I become employed.
            <br>_____ I have read, understand, and agree to follow the rules listed above.
            <br>Transportation
            <br>I understand that I am not allowed to have a vehicle while in residency at Butterfly House. I agree that I will not “hide” a vehicle to use covertly while in residency at Butterfly House.
            <br>I understand that transportation provided by staff is a privilege, and temporary, until I receive my first paycheck. I understand that when I become employed, I will be required to establish a ride to and from my place of employment and will pay whatever fee is established between my self and my transporter.
            <br>I understand and agree that residents on probation that request transportation from Butterfly House staff for probation appointments in Balsam Lake, WI will be required to pay $5 per resident, per ride. Fee must be paid at time of transport. Transportation will be provided by staff if staff is available, otherwise residents must establish their own transportation to meet with their probation officer.
            <br>I understand that Butterfly House staff will provide transportation for house activities (Second Sunday, “away” meetings, etc.). I understand that I will need to find my own transportation to personal appointments or pay an agreed upon fee to staff for transportation.
            <br>I agree that if I use a bicycle belonging to Butterfly House, I will return it in working order, and in the same condition I received it in. I will use a bike lock to secure the bike when not on the grounds of Butterfly House. I will return the bike lock with the key or I agree that I will purchase a new bike lock to replace the one I lost.
            <br>_____ I have read, understand, and agree to follow the rules listed above.
            <br>6
            <br>
            <strong>Relationships</strong>
            <br>I agree that I will not correspond with, or have contact with boyfriends, former boyfriends, male BF’s, male “acquaintances”, males that I have met while in treatment, males that I had corresponded with while incarcerated, males I have met while at a meeting, former dealers, former “using friends” while I am a resident of Butterfly House. I will not correspond in any way with males and females that I have a “no contact” order with. I will not ride in a vehicle with any male included in the above list while I am a resident of Butterfly House. I will not ask for, or accept phone numbers or e-mail addresses from anyone listed above. I will not correspond on Facebook with any person listed above. I agree that if I have a question about this rule, I will ask staff for clarification.
            <br>I agree that all relationships with other persons (male or female) are to be friendships…period. I acknowledge that I am not allowed to date, have sexual relations with, “hook-up”, or have other than a platonic friendship with any other person (male or female) while a resident of Butterfly House.
            <br>I agree that I will not attend “fellowship” with only persons of the opposite sex. I will not receive rides to and from meetings or other places from a person of the opposite sex.
            <br>I agree that I will not date, have sexual relations with, "hook-up”, or have other than a platonic friendship with any other 12 step meeting participant (male or female) before, during, or after AA or other 12 step meeting while I am a resident of Butterfly House.
            <br>I agree that I will not have an exclusive relationship with any other resident of Butterfly House. I will not have sexual relations, “hook-up”, or have other than a platonic friendship with any other resident of Butterfly House.
            <br>I will not have an exclusive relationship with any member of Butterfly House staff, Advisory Board, or volunteer of Butterfly House. I will not engage in non-group activities or other-than-platonic behavior with any staff or volunteers of Butterfly House.
            <br>I agree that I will not have an “other-than-platonic” relationship with my recovery sponsor. I acknowledge that female residents are required to have a female sponsor.
            <br>Failure to follow the above outlined rules may result in being put on contract or possibly expulsion from Butterfly House, depending on the circumstance.
            <br>_____ I have read, understand, and agree to follow the rules listed above.
            <br>Probation/parole/court orders/mental health commitments
            <br>I agree that I will comply with all Wisconsin Department of Community Corrections Rules regarding my probation (if applicable). I understand that if I violate the Wisconsin Department of Community Corrections Rules regarding my probation, my probation officer will be notified immediately.
            <br>I agree to comply with all conditions of a bond or judge’s order. I understand that if I violate a judge’s order or condition of bond, law enforcement will be notified and it will be grounds for immediate expulsion from Butterfly House.
            <br>I understand that if I am on probation/parole and I violate my probation/parole rules or break societal laws in any way, my probation officer and/or law enforcement will be notified immediately.
            <br>I understand that if I am under a mental health commitment order and I violate the guidelines of that order, my social worker and/or law enforcement will be notified immediately.
            <br>_____ I have read, understand, and agree to follow the rules listed above.
            <br>7
            <br>
            <strong>12 Step and other Required Meetings</strong>
            <br>I agree that I will participate in all mandatory meetings including AA or other 12 step support meetings, house meetings, and all other resident activities assigned by staff.
            <br>I agree that I will protect the identity and confidentiality of all meeting participants. This means I will not share the name or identity of meeting participants with others outside of the 12 Step Meeting. I will not share the content of another meeting participant’s testimony with others outside of the 12 Step Meeting.
            <br>I agree that I will act in a respectful manner while in the presence of all 12 Step Meeting participants. This means that during the meeting, I will sit quietly and listen to the testimony of all participants of that meeting. When it is my turn to speak, I will not “pass”. I will contribute equally to the group. I will refrain from using profanities while talking within the meeting or while on the meeting property. When participants “count off” for the purpose of forming a group, I will attend the group with my number.
            <br>I agree that I will not practice the “13th Step”. This means I will not pursue a romantic relationship with any meeting participant. I will not act in an overt, flirtatious manner with any meeting participant. I will not ask for full names or phone numbers from a meeting participant with the intent to pursue a romantic relationship. I will not give my full name or phone number to any meeting participant except my sponsor. I will not give the phone number of Butterfly House to any meeting participant. I will not make covert plans to meet with, or correspond with meeting participants of the opposite sex.
            <br>I agree that I will not discuss the personal business of other Butterfly House residents or staff with another 12 Step Meeting participants, my sponsor, my family, my friends, or any other person that does not reside at Butterfly House.
            <br>I agree to be continually working a 12-step recovery program under the guidance of a sponsor throughout my residency at Butterfly House. I agree to obtain a sponsor of my choosing within the first 2 weeks of residency at Butterfly House.
            <br>I agree that I will not text message, doodle, draw, sleep, listen to music, or act in any other distracted manner while attending a 12 Step Meeting. This means I will not borrow a phone to text someone inside or outside of the group. I will not get up to get coffee or other food or beverage. I will not walk around the room while the group is in session. I will not talk or whisper to other meeting participants while the meeting is in session.
            <br>I agree that I will not pursue a relationship with, or make plans to correspond with Hazelden Treatment Center (or any other treatment center) clients. I will act appropriately and accordingly around all meeting participants.
            <br>I agree that I will not “bum” cigarettes, “borrow” money, or accept donations of money or other items from other meeting participants.
            <br>I agree that my outward appearance is a good indicator of what I am striving to be on the inside. I will not wear low cut shirts. I will not wear short skirts or short shorts. If I wear jeans with holes, I will make sure the holes are not in the seat or crotch area. I will always wear undergarments (bra, underwear).
            <br>_____ I have read, understand, and agree to follow the rules listed above.
            <br>8
            <br>
            <strong>Drug Testing (UA, ETG, PBT, etc.)</strong>
            <br>I understand and agree that I will be tested randomly for illicit drug use, alcohol use, and/or prescription drug abuse at any time during my residency at Butterfly House.
            <br>I understand that after 30 days of residency, I am eligible to apply for an overnight pass and my destination must be approved at the time of my request. I agree to supply contact information for my destination. I understand that all requests must be made at least 24 hours in advance of LOA—NO EXCEPTIONS! I understand that upon return, I will be given a UA, ETG, and PBT. Cost for ETG is $20 and must be paid at the time of the test.
            <br>I understand that if drug use is suspected and I take a UA or ETG test, if the test is positive, I will be charged a $20 fee. I understand that I can refuse the test and not have to pay the $20, but the consequence will be immediate expulsion from the Butterfly House program.
            <br>I understand and agree that I will be given a UA, PBT, and ETG test upon return from a leave of absence. The fee for this test is $20 and must be paid at the time of the test. Refusal to take any drug test will be treated as a positive result and the consequence will be immediate expulsion from the Butterfly House program.
            <br>I agree to follow all curfews. I will be on property of Butterfly House by 10 pm on Sunday through Thursday evening. I will be on property by 11 pm on Friday and Saturday evenings. I understand that if I am late for curfew, I will be given a drug/alcohol test at my expense ($20). Refusal of a UA or PBT will result in expulsion from residency. I agree that I will be up in the morning by 7:30 am on Monday through Friday. I will be up in the morning by 8:30 am on Saturdays and 8 am on Sundays.
            <br>I understand that refusal to take a PBT (breathalyzer) UA, or ETG test will be treated as a positive result. The consequence of drug use or abuse is immediate expulsion from the Butterfly House program.
            <br>I understand that if I am late for curfew, even 5 minutes, I will be given a UA and/or PBT at my expense ($20).
            <br>_____ I have read, understand, and agree to follow the rules listed above.
        </p>
        <h3 align="center">
            <!-- end #mainContent -->
        </h3>
        <div class="box">
            <p>I ______________________________________, understand that my term of stay at Butterfly House is limited to 6 months with the opportunity to apply for an extension after I have been a resident in good standing for 3 months. If it is determined by Butterfly House staff and Board that I have not complied with rules and expectations, I will be assisted with finding options for an alternative living situation. I understand that it is ultimately my responsibility to find an alternative living situation if I violate the rules or have not fulfilled goals and expectations of residency at Butterfly House.
                <br>I, _____________________________________________ have read, understand, and agree to follow Butterfly House program rules and expectations. I understand that safety violations or continuous violation of minor rules will be grounds for immediate expulsion from residency at Butterfly House.
                <br>Signed _______________________________________________ Date _____/_____/_____
            </p>
        </div>
        <p align="center">&nbsp;</p>
    </div>
</template>

<script>
export default {};
</script>

<style>
</style>
